<?php

namespace PHLU\Neos\Models\Aspects;


use PHLU\Evento\Service\Contact\ImportService;
use TYPO3\Flow\Annotations as Flow;
use TYPO3\Flow\Aop\JoinPointInterface;

/**
 * @Flow\Scope("singleton")
 * @Flow\Aspect
 */
class AutogeneratedContactsListAspect
{


    /**
     * @Flow\Inject
     * @var ImportService
     */
    protected $importService;

    /**
     * @Flow\Before("within(TYPO3\TYPO3CR\Domain\Repository\NodeDataRepository) && method(public .+->(update|add)(object.nodeType.name == 'PHLU.Corporate:SectionAutoGeneratedContentContactsList'))")
     * @return void
     */
    public function update(JoinPointInterface $joinPoint)
    {


        $object = $joinPoint->getMethodArgument('object');
        /* @var \TYPO3\TYPO3CR\Domain\Model\NodeData $object */
        $this->importService->updateAutogeneratedContactsListFromNodeData($object);


    }



}
